### ISSUE TITLE
Section numbering style

### ISSUE THREAD

**Issue by shaymush** [eyalroz/technion-iit-thesis#25]
Section 2 heading in Chapter 1 appears as 2.1

How can I change its order?
Instead of 2.1 I want it to show 1.2

**Comment by shaymush** [comment]
Actually it seems that all numbers in this section appears in the opposite direction.
How can I change it?

**Comment by eyalroz** [comment]
Are you describing a problem with the compilation of sample thesis, or with your own thesis?

**Comment by shaymush** [comment]
With the compilation of sample thesis.
I want to change it in my thesis.

**Comment by shaymush** [comment]
![image](https://user-images.githubusercontent.com/7659337/35480587-036a7f42-041a-11e8-9c92-0d7907d8fb42.png)

**Comment by eyalroz** [comment]
Well, then, this is not an issue why my document class or template - at least, not that we know of - since they don't exhibit this.

I suggest you try tex.stackexchange.com. Specifically, perhaps one of [these questions](https://tex.stackexchange.com/search?q=%5Bhebrew%5D+reverse) might help, and if they don't, write your own question there. You will need to create a minimal test case for this happening though.

**Comment by shaymush** [comment]
I'm using the Overleaf version published in 
https://www.overleaf.com/latex/templates/tagged/technion

I can see this issue exists there too.

**Comment by shaymush** [comment]
![image](https://user-images.githubusercontent.com/7659337/35480843-450446f8-0420-11e8-8e52-67b916fcdba0.png)

all the numbers at the table of content are opposite

**Comment by eyalroz** [comment]
At the Overlead link there are two versions available. Which of them

**Comment by eyalroz** [comment]
So, apparently, it's not really a discrepancy between the code here in the repository and on Overleaf, it's actually different behavior of different versions of certain parts of the LaTeX distribution - since I'm seeing this manifest on a GNU/Linux Fedora 26 machine at work, but not on a GNU/Linux Mint 18.3 machine at home. @shaymush : Can you check on a Windows or a Mac machine, with the latest possible TeX distribution?

**Comment by eyalroz** [comment]
The problem can be narrowed down to the following example:
```
\documentclass{minimal}
\RequirePackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{hebrew}
\begin{document}
This sentence should have 2 before the point (not after it!): 2.
\end{document}
```
Please try compiling it. I just [asked the gurus](https://tex.stackexchange.com/q/413445/5640) about this.

**Comment by eyalroz** [comment]
@shaymush  : Ok, it turns out this is a bug with TeXLive, or the specific combination of packages there. If you install the latest TeXLive the numbers should come out fine.
