### ISSUE TITLE
Add use of cleveref package, add a more intuitive place/places for user package definitions.

### ISSUE THREAD

**Issue by ohadlor** [eyalroz/technion-iit-thesis#60]
I suggest the addition of the cleveref package to be used instead of autoref. Allows for lowercase and uppercase references. My issue with it seems to be a compatibility issue with some of your lemma definitions.
I also suggest adding a file that is inserted into iitthesis-extra with user defined packages.

**Comment by eyalroz** [comment]
> I also suggest adding a file that is inserted into iitthesis-extra with user defined packages.

1. Separate issue.
2. You can add any package you like into the document header - like with any LaTeX document class: After the `\documentclass`, before the `\begin{document}`.

**Comment by eyalroz** [comment]
> I suggest the addition of the cleveref package to be used instead of autoref. 

`\autoref` is provided by the `\hyperref` package, which is necessary AFAICT for generating in-document hyperlinks. So, we get it "for free". Naturally, I would rather minimize the package dependencies...

As for `cleveref` - IIANM, it is an abandoned package, unmaintained since 2018. See [this discussion on TeX.SX](https://tex.stackexchange.com/q/711418/5640). The suggestions there might help you make it work. I would need a strong argument for why it should be used in the document class.

**Comment by ohadlor** [comment]
I see, thanks for the input
